// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v2/healthcheck": {
            "get": {
                "description": "Retorna status OK se a API estiver no ar",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Verificação de saúde",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/recomendacoes": {
            "post": {
                "description": "Dispara processo assíncrono para gerar recomendações para todos os clientes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recomendacoes"
                ],
                "summary": "Gera recomendações em massa",
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v2/recomendacoes/{clienteId}": {
            "get": {
                "description": "Retorna as últimas recomendações geradas para o cliente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recomendacoes"
                ],
                "summary": "Busca recomendações recentes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Cliente",
                        "name": "clienteId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dominio.ResultadoRecomendacao"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Gera e persiste novas recomendações para o cliente informado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recomendacoes"
                ],
                "summary": "Gera novas recomendações",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do Cliente",
                        "name": "clienteId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dominio.ResultadoRecomendacao"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dominio.Produto": {
            "type": "object",
            "properties": {
                "aplicacao_minima": {
                    "type": "number"
                },
                "id_produto": {
                    "type": "string"
                },
                "nome_produto": {
                    "type": "string"
                },
                "rentabilidade_12m": {
                    "type": "number"
                },
                "risco_associado": {
                    "type": "string"
                }
            }
        },
        "dominio.RecomendacaoItem": {
            "type": "object",
            "properties": {
                "motivo": {
                    "type": "string"
                },
                "pontuacao": {
                    "type": "number"
                },
                "produto": {
                    "$ref": "#/definitions/dominio.Produto"
                }
            }
        },
        "dominio.ResultadoRecomendacao": {
            "type": "object",
            "properties": {
                "id_cliente": {
                    "type": "string"
                },
                "id_recomendacao": {
                    "description": "uuid gerado",
                    "type": "string"
                },
                "recomendacoes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dominio.RecomendacaoItem"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Recomendações",
	Description:      "Microsserviço de recomendações com estratégia Strangler Fig para legado.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
